package Inheritance;

/**
 * ABSTARCT CLASSIN EN ÖNEMLİ AVANTAJI
 * İÇİNDE BELİRTTİĞİMİZ METODLARDA TÜRETİLEN CLASSLAR İÇİN
 * ORTAK OLAN METHODLARIN GÖVDELERİ YAZILARAK GEREKSİZ YERE KOD YAZILMASI
 * ENGELLENİR
 * FAKRLILASAN METHODLARDA İSE SADECE BASLIK YAZILARAK OVERRIDE EDİLEBİLR
 */
public class AbsttraactClass {
}
